# Generated by Django 3.2.10 on 2022-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(max_length=100)),
                ('utility_rate', models.CharField(max_length=100)),
                ('information', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
