# Generated by Django 3.2.10 on 2022-12-28 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_spreadsheetuserrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_role',
            field=models.CharField(default='company_admin', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('ticket_type', models.CharField(max_length=30)),
                ('spreadsheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.spreadsheet')),
                ('user_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticker_user_assigned', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticker_user_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
