# Generated by Django 3.2.10 on 2022-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_solararray_number_of_solar_panels'),
    ]

    operations = [
        migrations.AddField(
            model_name='solararray',
            name='pvwatts_object_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
