# Generated by Django 3.2.10 on 2022-10-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_solararray_pvwatts_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
