# Generated by Django 3.2.10 on 2022-11-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_utility_rate_moneyrate_rate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem',
            name='money_rate_object',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.moneyrate'),
        ),
    ]
