# Generated by Django 3.2.10 on 2022-12-28 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221228_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 21, 14, 32, 53780)),
            preserve_default=False,
        ),
    ]
