# Generated by Django 3.2.10 on 2022-12-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheetrow',
            name='pending_in_ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ticket'),
        ),
    ]
