# Generated by Django 3.2.10 on 2022-10-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_inverter_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarEdgeSystemActualEnergyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('output', models.JSONField()),
                ('last_requested_date', models.DateField(blank=True, null=True)),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.solarsystem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
