# Generated by Django 3.2.10 on 2022-12-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_solarsystem_money_rate_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolarEdgeSystemActualEnergyProduction',
            new_name='SystemActualEnergyProduction',
        ),
        migrations.RenameField(
            model_name='moneyrate',
            old_name='information',
            new_name='rate_structure',
        ),
    ]
