# Generated by Django 3.2.10 on 2022-10-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_solaredgesystemactualenergyproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='primary_module',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inverter',
            name='connected_optimizers',
            field=models.IntegerField(default=0),
        ),
    ]
