# Generated by Django 3.2.10 on 2022-12-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221207_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoneyRate',
            new_name='UtilityRate',
        ),
    ]
