# Generated by Django 3.2.10 on 2022-12-12 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_moneyrate_utilityrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='solararray',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solarsystem'),
        ),
        migrations.AlterField(
            model_name='solararray',
            name='inverter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.inverter'),
        ),
        migrations.CreateModel(
            name='MicroInverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(default='', max_length=100)),
                ('capacity', models.IntegerField(default=0)),
                ('connected_optimizers', models.IntegerField(default=0)),
                ('sku', models.CharField(default='', max_length=100)),
                ('part_number', models.CharField(default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.solararray')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.solarsystem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
