# Generated by Django 3.2.10 on 2022-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221027_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='part_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inverter',
            name='sku',
            field=models.CharField(default='', max_length=100),
        ),
    ]
