# Generated by Django 3.2.10 on 2023-01-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_spreadsheetrow_number_of_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ticketparent'),
        ),
    ]
