# Generated by Django 3.2.10 on 2023-01-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230126_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheetrow',
            name='pending_in_ticket',
        ),
        migrations.AddField(
            model_name='spreadsheetrow',
            name='pending_in_ticket_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ticketparent'),
        ),
    ]
