# Generated by Django 3.2.10 on 2022-12-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221212_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem',
            name='api_name',
            field=models.CharField(default='SolarEdge', max_length=100),
            preserve_default=False,
        ),
    ]
