# Generated by Django 3.2.10 on 2023-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230126_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rows_count',
            field=models.IntegerField(default=0),
        ),
    ]
