# Generated by Django 3.2.10 on 2022-12-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_solarsystem_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microinverter',
            name='array',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solararray'),
        ),
    ]
