# Generated by Django 3.2.10 on 2023-01-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ticket_rows_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
