# Generated by Django 3.2.10 on 2023-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ticket_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sports',
            field=models.BooleanField(default=False),
        ),
    ]
